spring:
  application:
    name: file-app

  datasource:
    url: jdbc:mysql://192.168.0.106/filedata?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
     # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
     initialSize: 5
     minIdle: 5
     maxActive: 20
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 6000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false

flyway:
  baselineOnMigrate: true
  locations: classpath:db/migration/{vendor}
  enabled: true
  sql-migration-prefix: V
  sql-migration-suffix: .sql

server:
  port: 10401

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.devchen.file.dal.entity
  config-location: classpath:mybatis-config.xml
  check-config-location: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.106:10001/eureka/

download:
  logSaveDir: /root/spring-cloud/file-app/download-logs