spring:
  application:
    name: config-app

  cloud:
    config:
      label: master

      server:
        git:
          uri: https://github.com/jacoy519/config-repo/
          searchPaths: repo


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/