spring:

  datasource:
    url: jdbc:mysql://104.224.146.106/spddata?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: C5h8e6n0Qianhmasfgasdasqwe12341256asddhsfggsd
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

server:
  port: 10601

zod:
  username: medivh
  password: Chen5860Qi


proxy:
  out: 162.219.122.251:10801


